version: '3.8'

services:
  nginx:
    restart: always
    build:
      context: ./compose/local/nginx
      dockerfile: Dockerfile
    ports:
      - '3040:80'

  backend:
    build:
      context: .
      dockerfile: ./compose/test/backend/Dockerfile
    command: /start.sh
    environment:
      - MONGO_URI=mongodb://db/nutristrat_test
      - DB_HOST=db
      - DB_PORT=27017
      - NODE_ENV=test
      - PORT=8000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mongo:4.4
    restart: always

  frontend:
    build:
      context: .
      dockerfile: ./compose/test/frontend/Dockerfile
    command: /start.sh
    volumes:
      - /app/node_modules
      - ./frontend:/usr/src/app
    environment:
      - API_HOST=http://backend:8000
    ports:
      - 3000:3000
