version: '3.8'

services:
  nginx:
    restart: always
    build:
      context: ./compose/local/nginx
      dockerfile: Dockerfile
    ports:
      - '3050:80'

  backend:
    build:
      context: .
      dockerfile: ./compose/test/backend/Dockerfile
    command: /start.sh
    environment:
      - MONGO_URI=mongodb://db/nutristrat_test
      - DB_HOST=db
      - DB_PORT=27017
      - NODE_ENV=test
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mongo:4.4
    restart: always

  frontend:
    build:
      context: .
      dockerfile: ./compose/test/frontend/Dockerfile
    command: /start.sh
    environment:
      - API_HOST=http://backend:5000
    ports:
      - 3000:3000
    depends_on:
      - backend

  cypress:
    build:
      context: .
      dockerfile: ./compose/test/e2e/Dockerfile
    environment:
      - MONGO_URI=mongodb://db/nutristrat_test
      - DB_HOST=db
      - DB_PORT=27017
      - NODE_ENV=test
    depends_on:
      - backend
      - frontend
