version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./compose/test_backend/backend/Dockerfile
    command: /start.sh
    environment:
      - MONGO_URI=mongodb://db/nutristrat_test
      - DB_HOST=db
      - DB_PORT=27017
      - NODE_ENV=test
      - PORT=8000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mongo:4.4
    restart: always
